Updated workflow to clean toolchain cache before itself

diff --git a/.github/workflows/checkloading.yml b/.github/workflows/checkloading.yml
--- a/.github/workflows/checkloading.yml
+++ b/.github/workflows/checkloading.yml
@@ -1,16 +1,19 @@
+
+
+
+
+
 name: Loading check
 on:
   pull_request:
   workflow_dispatch:
   push:
-     branches: [ "main" ]
+    branches: [ "main" ]
   merge_group:
   schedule:
-  - cron:  0 23 * * *
-
+    - cron: 0 23 * * *
 env:
   GO_VERSION: '1.22'
-
 jobs:
   build:
     name: building defsec
@@ -18,15 +21,17 @@ jobs:
     strategy:
       matrix:
         os: [ macos-latest, windows-latest, ubuntu-latest ]
-
     steps:
     - uses: actions/checkout@v4
-
-    - uses: lmvysakh/setup-go@test_515_2
-    # - uses: antontroshin/setup-go@windows-go-mod-cache
+    # Cleanup conflicting Go toolchain cache files on macos and ubuntu to prevent tar extraction errors
+    - name: Clean Go toolchain cache directory (macos & ubuntu)
+      if: matrix.os == 'macos-latest' || matrix.os == 'ubuntu-latest'
+      run: |
+        echo "Cleaning Go toolchain cache directory to avoid 'File exists' errors"
+        rm -rf $HOME/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.24.0.*
+    - uses: lmvysakh/setup-go@test_515
       with:
         go-version: ${{ env.GO_VERSION }}
-
     - name: go mod tidy
       if: matrix.os == 'ubuntu-latest'
       run: |
@@ -43,3 +48,65 @@ jobs:
       if: matrix.os == 'ubuntu-latest'
       run: make test
       shell: bash
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+
+# Old workflow
+# name: Loading check
+# on:
+#   pull_request:
+#   workflow_dispatch:
+#   push:
+#      branches: [ "main" ]
+#   merge_group:
+#   schedule:
+#   - cron:  0 23 * * *
+
+# env:
+#   GO_VERSION: '1.22'
+
+# jobs:
+#   build:
+#     name: building defsec
+#     runs-on: ${{ matrix.os }}
+#     strategy:
+#       matrix:
+#         os: [ macos-latest, windows-latest, ubuntu-latest ]
+
+#     steps:
+#     - uses: actions/checkout@v4
+
+#     - uses: lmvysakh/setup-go@test_515_2
+#     # - uses: antontroshin/setup-go@windows-go-mod-cache
+#       with:
+#         go-version: ${{ env.GO_VERSION }}
+
+#     - name: go mod tidy
+#       if: matrix.os == 'ubuntu-latest'
+#       run: |
+#         go mod tidy
+#         if [ -n "$(git status --porcelain)" ]; then
+#           echo "Run 'go mod tidy' and push it"
+#           exit 1
+#         fi
+#     - name: Run non-localstack tests
+#       if: matrix.os != 'ubuntu-latest'
+#       run: make test-no-localstack
+#       shell: bash
+#     - name: Run full tests
+#       if: matrix.os == 'ubuntu-latest'
+#       run: make test
+#       shell: bash
